#!/bin/bash

ssh_url=$(git remote -v | grep magrit | grep push | cut -f2 | cut -d" " -f1)

ssh_url=${ssh_url:6}
user=${ssh_url%@*}
ssh_url=${ssh_url#*@}
host=${ssh_url%:*}
ssh_url=${ssh_url#*:}
port=${ssh_url%/*}
repo="/${ssh_url#*/}/"

commit=$(git rev-parse HEAD)

status=$(ssh -x -p $port $user@$host "magrit status $repo $commit")

echo "# Commit $(git log -1 --oneline $commit)"
echo "# ${status}"

