#!/bin/bash
# Copyright 2011 Frederic Menou
#
# This file is part of Magrit.
#
# Magrit is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Magrit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with Magrit.
# If not, see <http://www.gnu.org/licenses/>.

# Completion setup for bash
# to be put in /etc/completion.d
# Can be used as it with :
# source magrit

function _magrit {
	local cur cmds opts
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	opts="-h --help"
	cmds="build-log cat-build config monitor send-build share status"
	
	if [[ ${cur} == -* ]]
	then
		case $prev in
		magrit)
			COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
			return 0
			;;
		esac
	else
		case $prev in
		config)
			COMPREPLY=( $(compgen -W "add use rm" -- ${cur}) )
			return 0
			;;
		magrit)
			COMPREPLY=( $(compgen -W "${cmds}" -- ${cur}) )
			return 0
			;;
		esac
	fi
	
}

complete -F _magrit magrit
