#!/bin/bash
# Copyright 2011-2012 Frederic Menou and others referred in AUTHORS file.
#
# This file is part of Magrit.
#
# Magrit is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Magrit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with Magrit.
# If not, see <http://www.gnu.org/licenses/>.

# magrit config add (--alias alias) (localhost(:2022)) project-name
# magrit config use alias
# magrit config rm alias

function help {
	cat <<__HELP__
usage: magrit config add [--alias name] [host:port] project-name
   or: magrit config use name
   or: magrit config rm name
__HELP__
}

cmd=$1
shift 1

if [ $cmd = "--help" -o $cmd = "-h" ]
then
	help
	exit 0
fi

if [ $# -eq 0 ]
then
	echo "Bad syntax: missing sub command"
	help
	exit 1
fi

if [ $cmd = "add" ]
then
	aliasName="magrit"
	if [ $1 = "--alias" ]
	then
		aliasName=$2
		shift 2
	fi
	
	user=$LOGNAME
	host="localhost:2022"
	if [ $# -eq 2 ]
	then
		host=$1
		shift 1
	fi
	
	projectName=$1
	
	url="ssh://$user@$host/$projectName"
	
	git remote add $aliasName $url
elif [ $cmd = "use" ]
then
	aliasName=$1
	git config magrit.remote $aliasName
elif [ $cmd = "rm" ]
then
	aliasName=$1
	git remote rm $aliasName
else
	echo "Bad syntax: unrecognized argument $1"
	help
	exit 1
fi
