#!/bin/bash

if [ $# -ge 1 ]
then
	if [ $1 = "--version" ]
	then
		echo ${project.version}
	elif [[ $(which magrit-$1) ]]
	then
		command=$1
		shift 1
		magrit-$command "$@"
	else
		echo "Magrit: commande magrit $1 inconnue."
	fi
fi

