#!/bin/bash -e

source utils

_checkSsh

_colorize "## send build" 37

force=""
command=""
while [ "${1:0:2}" = "--" ]; do
	if [ "$1" = "--force" ]; then
		force="$1"
		shift 1
	elif [ "$1" = "--command" ]; then
		command="$1 $2"
		shift 2
	fi
done

if [ $# -gt 0 ]; then
	revstr=$1
else
	revstr="-1 HEAD"
fi

repo=${_target[$_REPO]}

in="/tmp/magrit-${BASHPID}-in"
out="/tmp/magrit-${BASHPID}-out"

mkfifo $in $out

_sendSshCommandBg $in $out magrit send-build $force $command $repo -

exec 3<$out

for sha1 in $(git log --format=%H $revstr); do
	echo $sha1 >$in
	read -u 3 status
	
	if [[ "$status" =~ "ssh error: *" ]]; then
		echo $status >&2
	else
		statusText=$(_colorize "Submitted" 92)
		if [ "$status" -eq 0 ]; then
			statusText=$(_colorize "Skipped" 37)
		fi

		log=$(git log --color=$_colorAction -1 --oneline $sha1 -z)
						
		echo -e "$(_ellipsis "$log") | $statusText"
	fi
	
done

echo "--" >$in
exec 3<&-

rm $in $out
for pid in $(jobs -p); do
	kill -s TERM $pid
done
