#!/bin/bash
# Copyright 2011 Frederic Menou
#
# This file is part of Magrit.
#
# Magrit is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Magrit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with Magrit.
# If not, see <http://www.gnu.org/licenses/>.

if [ $# -ge 1 ]
then
	if [ $1 = "--version" ]
	then
		echo ${project.version}
	elif [[ $(which magrit-$1) ]]
	then
		command=$1
		shift 1
		magrit-$command "$@"
	else
		echo "Magrit: commande magrit $1 inconnue."
	fi
fi

