#!/bin/bash -e

source utils

_getSsh
repo=${_target[$_REPO]}

revstr="HEAD"
if [ $# -gt 0 ]; then
	revstr=$1
fi

commit=$(git rev-parse $revstr)

status=$(_sendSshCommand magrit status $repo $commit)

echo "# $(git log --color=$_colorAction -1 --oneline $commit)"
echo "$(_colorizeStatus $status)"
