#!/bin/bash -e
# Copyright 2011 Frederic Menou
#
# This file is part of Magrit.
#
# Magrit is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Magrit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with Magrit.
# If not, see <http://www.gnu.org/licenses/>.

# magrit status

function help {
	cat <<__HELP__
usage: magrit status <commit>
__HELP__
}

if [ $# -gt 0 ]; then
	if [ $1 = "-h" -o $1 = "--help" ]; then
		help
		exit 0
	fi
fi

source utils

_checkSsh
repo=${_target[$_REPO]}

revstr="HEAD"
if [ $# -gt 0 ]; then
	revstr=$1
fi

commit=$(git rev-parse $revstr)

status=$(_sendSshCommand magrit status $repo $commit)

echo "# $(git log --color=$_colorAction -1 --oneline $commit)"
echo "$(_colorizeStatus $status)"
