#!/bin/bash -e

source utils

remote=$(_getRemote)

revstr="HEAD"
if [ $# -gt 0 ]; then
	revstr="$1"
fi

commit=$(git rev-parse --verify "$revstr")

git push --force $remote $revstr
magrit build send "-1 $commit"

