#!/bin/bash -e

# magrit build send (--force) ~sha1

source utils

if [ $1 = "send" ]; then
	shift 1
	force=""
	if [ "$1" = "--force" ]; then
		force="--force"
		shift 1
	fi
	if [ $# -gt 0 ]; then
		revstr=$1
	else
		revstr="-1 HEAD"
	fi
	
	_getSsh
	user=${_target[$_USER]}
	host=${_target[$_HOST]}
	port=${_target[$_PORT]}
	repo=${_target[$_REPO]}

	for sha1 in $(git log --format=%H $revstr); do
		command="magrit build send $force $repo $sha1"
		#echo -e "ask build for $(_colorize $sha1 31)"
		ssh -x -p $port $user@$host $command
	done
fi
