#!/bin/bash -e 

source utils

_getSsh
repo=${_target[$_REPO]}

for sha1 in $(git log --format=%H $1); do
	log=$(git log --color=$_colorAction -1 --oneline $sha1 -z)

	buildStatus=$(_sendSshCommand magrit status $repo $sha1)
	buildStatus=$(_colorizeStatus $buildStatus)
	
	echo -e "$(_ellipsis "$log") | $buildStatus"
done

