#!/bin/bash

# magrit config add (--alias alias) (localhost(:2022)) project-name
# magrit config use alias
# magrit config rm alias

function help {
	cat <<__HELP__
usage: magrit config add [--alias name] [host:port] project-name
   or: magrit config use name
   or: rm name
__HELP__
}

cmd=$1
shift 1

if [ $# -eq 0 ]
then
	echo "Bad syntax: missing sub command"
	help
	exit 1
fi

if [ $cmd = "help" ]
then
	help
elif [ $cmd = "add" ]
then
	aliasName="magrit"
	if [ $1 = "--alias" ]
	then
		aliasName=$2
		shift 2
	fi
	
	user=$LOGNAME
	host="localhost:2022"
	if [ $# -eq 2 ]
	then
		host=$1
		shift 1
	fi
	
	projectName=$1
	
	url="ssh://$user@$host/$projectName"
	
	git remote add $aliasName $url
elif [ $cmd = "use" ]
then
	aliasName=$1
	git config magrit.remote $aliasName
elif [ $cmd = "rm" ]
then
	aliasName=$1
	git remote rm $aliasName
else
	echo "Bad syntax: unrecognized argument $1"
	help
	exit 1
fi
