#!/bin/bash -e
# Copyright 2011 Frederic Menou
#
# This file is part of Magrit.
#
# Magrit is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Magrit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with Magrit.
# If not, see <http://www.gnu.org/licenses/>.

source utils

if [ "$1" = "--help" -o "$1" = "-h" ]
then
	echo "usage: magrit build-log [<git-log options>] [<since>..<until>]"
	exit 0
fi

_checkSsh

_colorize "## log" 37

repo=${_target[$_REPO]}

in="/tmp/magrit-${BASHPID}-in"
out="/tmp/magrit-${BASHPID}-out"

mkfifo $in $out

_sendSshCommandBg $in $out magrit status $repo -

exec 3<$out

for sha1 in $(git log --format=%H $1); do
	log=$(git log --color=$_colorAction -1 --oneline $sha1 -z)

	echo $sha1 >$in
	read -u 3 buildStatus
	
	echo -e "$(_ellipsis "$log") | $(_colorizeStatus $buildStatus)"
done

echo "--" >$in

exec 3<&-

rm $in $out
for pid in $(jobs -p); do
	kill -s TERM $pid
done
