#!/bin/bash -e

source utils

_getSsh
user=${_target[$_USER]}
host=${_target[$_HOST]}
port=${_target[$_PORT]}
repo=${_target[$_REPO]}

revstr="HEAD"
if [ $# -gt 0 ]; then
	revstr=$1
fi

commit=$(git rev-parse $revstr)

status=$(ssh -x -p $port $user@$host "magrit status $repo $commit")

echo "# $(git log --color=always -1 --oneline $commit)"
echo "$(_colorizeStatus $status)"
