#!/bin/bash -e

echo "## send build"

source utils

_getSsh

force=""
if [ "$1" = "--force" ]; then
	force="--force"
	shift 1
fi
if [ $# -gt 0 ]; then
	revstr=$1
else
	revstr="-1 HEAD"
fi

repo=${_target[$_REPO]}

in="/tmp/magrit-${BASHPID}-in"
out="/tmp/magrit-${BASHPID}-out"

mkfifo $in $out

_sendSshCommandBg $in $out magrit send-build $force $repo -

exec 3<$out

for sha1 in $(git log --format=%H $revstr); do
	log=$(git log --color=$_colorAction -1 --oneline $sha1 -z)

	echo $sha1 >$in
	read -u 3 status
		
	statusText=$(_colorize "Submitted" 92)
	if [ $status -eq 0 ]; then
		statusText=$(_colorize "Skipped" 37)
	fi
	
	echo -e "$(_ellipsis "$log") | $statusText"
	
done

echo "--" >$in
exec 3<&-

rm $in $out
for pid in $(jobs -p); do
	kill -s TERM $pid
done
