#!/bin/bash -e

source utils

_getSsh
repo=${_target[_REPO]}

# magrit cat-build <REVSTR>

if [ $# -gt 0 ]; then
	revstr=$1
else
	revstr="HEAD"
fi

sha1=$(git rev-parse --verify $revstr)
command="magrit cat-build $repo $sha1"
_sendSshCommand $command
