#!/bin/bash -e

# magrit build send (--force) ~sha1

source utils

if [ $1 = "send" ]; then
	shift 1
	force=""
	if [ "$1" = "--force" ]; then
		force="--force"
		shift 1
	fi
	if [ $# -gt 0 ]; then
		revstr=$1
	else
		revstr="-1 HEAD"
	fi
	
	_getSsh
	user=${_target[$_USER]}
	host=${_target[$_HOST]}
	port=${_target[$_PORT]}
	repo=${_target[$_REPO]}

	for sha1 in $(git log --format=%H $revstr); do
		command="magrit build send $force $repo $sha1"
		status=$(ssh -x -p $port $user@$host $command)
		if [ $status -eq 1 ]; then
			echo -e "build ask for $(git log --color=$_colorAction --oneline -1 $sha1 | cut -d" " -f1)"
		else
			echo -e "build skipped by server, use --force if you really want it!"
		fi
	done
fi
